name: Pull private repo

on:
 push:
    branches:
      - studenci
      - main

env:
  USER: jhkwapisz
  PRIVATE_REPO_NAME: Big-Data
  DESTINATION_FOLDER: Big-Data-studenci

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: ${{env.USER}}/${{ env.PRIVATE_REPO_NAME }}
        ref: studenci
        token: ${{ secrets.PAT }}
        fetch-depth: 0
    
    - name: Push to Public Repo
      uses: ad-m/github-push-action@master
      with:
          branch: studenci
          github_token: ${{ secrets.PAT }}
          force: true
          repository: jhkwapisz/Big-Data-studenci

